//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVN.RiotApi {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class UrlSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UrlSettings defaultInstance = ((UrlSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UrlSettings())));
        
        public static UrlSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ddragon.leagueoflegends.com/cdn/{0}/img/profileicon/{1}.png")]
        public string ProfileIcon {
            get {
                return ((string)(this["ProfileIcon"]));
            }
            set {
                this["ProfileIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ddragon.leagueoflegends.com/cdn/img/champion/splash/{0}_0.jpg")]
        public string ChampionSplash {
            get {
                return ((string)(this["ChampionSplash"]));
            }
            set {
                this["ChampionSplash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ddragon.leagueoflegends.com/cdn/{0}/img/champion/{1}.png")]
        public string ChampionSquare {
            get {
                return ((string)(this["ChampionSquare"]));
            }
            set {
                this["ChampionSquare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ddragon.leagueoflegends.com/cdn/{0}/img/spell/{1}.png")]
        public string Spell {
            get {
                return ((string)(this["Spell"]));
            }
            set {
                this["Spell"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ddragon.leagueoflegends.com/cdn/{0}/img/item/{1}.png")]
        public string Item {
            get {
                return ((string)(this["Item"]));
            }
            set {
                this["Item"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ddragon.leagueoflegends.com/cdn/{0}/img/mastery/{1}.png")]
        public string Mastery {
            get {
                return ((string)(this["Mastery"]));
            }
            set {
                this["Mastery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ddragon.leagueoflegends.com/cdn/{0}/img/rune/{1}.png")]
        public string Rune {
            get {
                return ((string)(this["Rune"]));
            }
            set {
                this["Rune"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://{1}.api.riotgames.com/lol/summoner/v4/summoners/by-account/{2}?api_key={0" +
            "}")]
        public string SummonerByAccount {
            get {
                return ((string)(this["SummonerByAccount"]));
            }
            set {
                this["SummonerByAccount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://{1}.api.riotgames.com/lol/summoner/v4/summoners/by-name/{2}?api_key={0}")]
        public string SummonerByName {
            get {
                return ((string)(this["SummonerByName"]));
            }
            set {
                this["SummonerByName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://{1}.api.riotgames.com/lol/match/v4/matchlists/by-account/{2}?api_key={0}")]
        public string Matchlist {
            get {
                return ((string)(this["Matchlist"]));
            }
            set {
                this["Matchlist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://{1}.api.riotgames.com/lol/match/v4/matches/{2}?api_key={0}")]
        public string Match {
            get {
                return ((string)(this["Match"]));
            }
            set {
                this["Match"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://{1}.api.riotgames.com/lol/spectator/v4/active-games/by-summoner/{2}?api_k" +
            "ey={0}")]
        public string CurrentGame {
            get {
                return ((string)(this["CurrentGame"]));
            }
            set {
                this["CurrentGame"] = value;
            }
        }
    }
}
