//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVN.RiotApi {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class VersionSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static VersionSettings defaultInstance = ((VersionSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new VersionSettings())));
        
        public static VersionSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6.24.1")]
        public string DDRAGON_ID {
            get {
                return ((string)(this["DDRAGON_ID"]));
            }
            set {
                this["DDRAGON_ID"] = value;
            }
        }
    }
}
