namespace SVN.RiotApi.ApiEnums
{
    public enum MathmakingQueue
    {
        ALL = -1,
        Custom = 0,
        HowlingAbyss1v1SnowdownShowdown = 72,
        HowlingAbyss2v2SnowdownShowdown = 73,
        SummonersRift6v6Hexakill = 75,
        SummonersRiftUltraRapidFire = 76,
        HowlingAbyssOneForAllMirrorMode = 78,
        SummonersRiftCoopvsAIUltraRapidFire = 83,
        TwistedTreeline6v6Hexakill = 98,
        ButchersBridge5v5ARAM = 100,
        SummonersRiftNemesis = 310,
        SummonersRiftBlackMarketBrawlers = 313,
        CrystalScarDefinitelyNotDominion = 317,
        SummonersRiftAllRandom = 325,
        SummonersRift5v5DraftPick = 400,
        SummonersRift5v5RankedSolo = 420,
        SummonersRift5v5BlindPick = 430,
        SummonersRift5v5RankedFlex = 440,
        HowlingAbyss5v5ARAM = 450,
        TwistedTreeline3v3BlindPick = 460,
        TwistedTreeline3v3RankedFlex = 470,
        SummonersRiftBloodHuntAssassin = 600,
        CosmicRuinsDarkStarSingularity = 610,
        SummonersRiftClash = 700,
        TwistedTreelineCoopvsAIIntermediateBot = 800,
        TwistedTreelineCoopvsAIIntroBot = 810,
        TwistedTreelineCoopvsAIBeginnerBot = 820,
        SummonersRiftCoopvsAIIntroBot = 830,
        SummonersRiftCoopvsAIBeginnerBot = 840,
        SummonersRiftCoopvsAIIntermediateBot = 850,
        SummonersRiftARURF = 900,
        CrystalScarAscension = 910,
        HowlingAbyssLegendofthePoroKing = 920,
        SummonersRiftNexusSiege = 940,
        SummonersRiftDoomBotsVoting = 950,
        SummonersRiftDoomBotsStandard = 960,
        ValoranCityParkStarGuardianInvasionNormal = 980,
        ValoranCityParkStarGuardianInvasionOnslaugh = 990,
        OverchargePROJECTHunters = 1000,
        SummonersRiftSnowARURF = 1010,
        SummonersRiftOneforAll = 1020,
        CrashSiteOdysseyExtractionIntro = 1030,
        CrashSiteOdysseyExtractionCadet = 1040,
        CrashSiteOdysseyExtractionCrewmember = 1050,
        CrashSiteOdysseyExtractionCaptain = 1060,
        CrashSiteOdysseyExtractionOnslaught = 1070,
        NexusBlitzNexusBlitz = 1200,
    }
}